name: build

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: |
          cd Flow.Launcher.Plugin.GitEasy
          dotnet restore

      - name: Build
        run: |
          cd Flow.Launcher.Plugin.GitEasy
          dotnet publish -c Release -r win-x64 --no-self-contained Flow.Launcher.Plugin.GitEasy.csproj

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Flow.Launcher.Plugin.GitEasy
          path: ./Flow.Launcher.Plugin.GitEasy/bin/Release/Plugins/Flow.Launcher.Plugin.GitEasy/win-x64/publish
